views_save.saved_view_type.*:
  type: config_entity
  label: 'Saved View type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
